### ISSUE TITLE
Missing file ?

### ISSUE THREAD

**Issue by RomyxBaps** [kissit/phpMyAnsibleAdmin#3]
Hi,

First of all, thank you for you repository ! It seems to be great !
I want to try it but I've an issue when I try to log in with the admin account. When I click on "Login", I'm not redirect because the page domain.tld/login/login doesn't exist.

I search on the repository and didn't find it, what is the cause of this 404 ?

Thank you

**Comment by RomyxBaps** [comment]
Hi,

Any news ? :)

**Comment by RomyxBaps** [comment]
Hmmm i'm using Nginx.
But thank you for the hint. I'm gonna try this tonight when I get home and I keep you in touch.

Thanks

**Comment by kissit** [comment]
Ahh, yea that would be why its not working.  I don't know the Nginx config off hand, but if it helps it *should* be the same as would be used for Wordpress with Nginx.

Also note that this project is by no means considered complete and is still very much a work in progress, though at this point has gone dormant for quite a while due to my schedule.  So just keep that in mind when you get in there.
